### ISSUE TITLE
apt repository

### ISSUE THREAD

**Issue by azlux** [thelounge/thelounge-deb#63] opened 2019-12-20 23:11 UTC
Hi,
I've setup my personal apt repository for some projects. It's great when speaking about upgrades.
I've setup an auto-update for thelounge (stable) releases based on github.

You can see it at : http://packages.azlux.fr/

I think it's can be really helpful for all users to have an apt repository.
I offer you the use of mine. If you can to use you're own, I can also help you to setup one.

Best regards,
Azlux

**Comment by xPaw** [comment] 2019-12-20 23:29
Mostly a duplicate of #55

**Closed by xPaw** 2019-12-20 23:29 UTC

**Comment by azlux** [comment] 2019-12-20 23:36
Ops, srry, I haven't see this issue.
